name: Cerdikiawan
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: 1
options:
  bundleIdPrefix: id.ac.binus.skripsicerdikiawan
  deploymentTarget:
    iOS: "17.0"
packages:
  supabase-swift:
    url: https://github.com/supabase-community/supabase-swift.git
    from: 2.5.1
targets:
  Cerdikiawan:
    type: application
    platform: iOS
    sources: [Cerdikiawan]
    resources: [Resources]
    info:
      path: Cerdikiawan/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UILaunchStoryboardName: "LaunchScreen"
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UISupportedInterfaceOrientations~iphone:
          [
            UIInterfaceOrientationPortrait,
            UIInterfaceOrientationPortraitUpsideDown,
            UIInterfaceOrientationLandscapeLeft,
            UIInterfaceOrientationLandscapeRight,
          ]
        UISupportedInterfaceOrientations~ipad:
          [
            UIInterfaceOrientationPortrait,
            UIInterfaceOrientationPortraitUpsideDown,
            UIInterfaceOrientationLandscapeLeft,
            UIInterfaceOrientationLandscapeRight,
          ]
    dependencies:
      - package: supabase-swift
        products:
          - Supabase
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: id.ac.binus.skripsicerdikiawan.Cerdikiawan
      INFOPLIST_FILE: Cerdikiawan/Info.plist
  CerdikiawanTests:
    type: bundle.unit-test
    platform: iOS
    sources: [CerdikiawanTests]
    dependencies:
      - target: Cerdikiawan
    info:
      path: CerdikiawanTests/Info.plist
      properties:
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleName: $(PRODUCT_NAME)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundlePackageType: BNDL
    settings:
      base:
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Cerdikiawan.app/Cerdikiawan"
        BUNDLE_LOADER: "$(TEST_HOST)"
schemes:
  Cerdikiawan:
    build:
      targets:
        Cerdikiawan: all
        CerdikiawanTests: all
    test:
      targets:
        - name: CerdikiawanTests
          gatherCoverageData: true
